// copies deployedAddresses.json into client/src/config.js for the frontend to import
const fs = require("fs");
const path = require("path");

const deployedPath = path.join(__dirname, "..", "deployedAddresses.json");
const clientConfigPath = path.join(__dirname, "..", "client", "src", "config.js");

if (!fs.existsSync(deployedPath)) {
  console.error("deployedAddresses.json not found. Run deploy first.");
  process.exit(1);
}

const addresses = JSON.parse(fs.readFileSync(deployedPath, "utf8"));

const content = `// Auto-generated by scripts/updateFrontend.js
export const CONTRACT_ADDRESSES = ${JSON.stringify(addresses, null, 2)};
`;

fs.writeFileSync(clientConfigPath, content, "utf8");
console.log("Wrote", clientConfigPath);
